#include "TicoShaders.h"

// ============================================================================
// Vertex Shader (shared by all effects)
// ============================================================================
const char* GetShaderVertexSource()
{
    return
        "#version 330 core\n"
        "layout (location = 0) in vec2 aPos;\n"
        "layout (location = 1) in vec2 aTexCoord;\n"
        "out vec2 TexCoord;\n"
        "void main() {\n"
        "   gl_Position = vec4(aPos, 0.0, 1.0);\n"
        "   TexCoord = aTexCoord;\n"
        "}\n";
}

// ============================================================================
// Fragment Shaders
// ============================================================================

// --- None (passthrough) ---
static const char* kShaderNone =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "void main() {\n"
    "    FragColor = texture(Source, TexCoord);\n"
    "}\n";

// --- LCD ---
static const char* kShaderLCD =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "uniform vec2 TextureSize;\n"
    "uniform vec2 OutputSize;\n"
    "void main() {\n"
    "    vec4 color = texture(Source, TexCoord);\n"
    "    vec2 fragCoord = TexCoord * OutputSize;\n"
    "    float gridX = mod(fragCoord.x, 3.0);\n"
    "    float gridY = mod(fragCoord.y, 3.0);\n"
    "    vec3 mask = vec3(1.0);\n"
    "    if (gridX < 1.0)       mask = vec3(1.0, 0.7, 0.7);\n"
    "    else if (gridX < 2.0)  mask = vec3(0.7, 1.0, 0.7);\n"
    "    else                   mask = vec3(0.7, 0.7, 1.0);\n"
    "    if (gridY < 1.0) mask *= 0.85;\n"
    "    FragColor = vec4(color.rgb * mask, color.a);\n"
    "}\n";

// --- xBRZ (simplified single-pass xBR upscaler) ---
static const char* kShaderXBRZ =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "uniform vec2 TextureSize;\n"
    "uniform vec2 OutputSize;\n"
    "\n"
    "#define EQ_THRESHOLD 15.0/255.0\n"
    "\n"
    "float cdist(vec4 A, vec4 B) {\n"
    "    vec4 diff = A - B;\n"
    "    return dot(diff, diff);\n"
    "}\n"
    "bool is_eq(vec4 A, vec4 B) {\n"
    "    return cdist(A, B) < EQ_THRESHOLD;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec2 pos = TexCoord * TextureSize;\n"
    "    vec2 f = fract(pos);\n"
    "    vec2 dx = vec2(1.0 / TextureSize.x, 0.0);\n"
    "    vec2 dy = vec2(0.0, 1.0 / TextureSize.y);\n"
    "    vec4 E = texture(Source, TexCoord);\n"
    "    vec4 B = texture(Source, TexCoord - dy);\n"
    "    vec4 D = texture(Source, TexCoord - dx);\n"
    "    vec4 F = texture(Source, TexCoord + dx);\n"
    "    vec4 H = texture(Source, TexCoord + dy);\n"
    "    vec4 res = E;\n"
    "    bool eLDiff = (B != H && D != F);\n"
    "    if (eLDiff) {\n"
    "        if (is_eq(D,B) && !is_eq(D,H) && !is_eq(B,F) && f.x < 0.5 && f.y < 0.5) res = D;\n"
    "        if (is_eq(B,F) && !is_eq(B,D) && !is_eq(F,H) && f.x >= 0.5 && f.y < 0.5) res = F;\n"
    "        if (is_eq(D,H) && !is_eq(D,B) && !is_eq(H,F) && f.x < 0.5 && f.y >= 0.5) res = D;\n"
    "        if (is_eq(H,F) && !is_eq(H,D) && !is_eq(F,B) && f.x >= 0.5 && f.y >= 0.5) res = F;\n"
    "    }\n"
    "    FragColor = res;\n"
    "}\n";



// --- Eagle ---
static const char* kShaderEagle =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "uniform vec2 TextureSize;\n"
    "uniform vec2 OutputSize;\n"
    "\n"
    "vec3 dtt = vec3(65536.0, 255.0, 1.0);\n"
    "float reduce(vec3 color) { return dot(color, dtt); }\n"
    "\n"
    "int GET_RESULT(float A, float B, float C, float D) {\n"
    "    int x = 0, y = 0, r = 0;\n"
    "    if (A == C) x++; else if (B == C) y++;\n"
    "    if (A == D) x++; else if (B == D) y++;\n"
    "    if (x <= 1) r++;\n"
    "    if (y <= 1) r--;\n"
    "    return r;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec2 texel = 1.0 / TextureSize;\n"
    "    float dx = texel.x;\n"
    "    float dy = texel.y;\n"
    "    vec2 fp = fract(TexCoord * TextureSize);\n"
    "\n"
    "    vec3 C0 = texture(Source, TexCoord + vec2(-dx, -dy)).rgb;\n"
    "    vec3 C1 = texture(Source, TexCoord + vec2(-dx,   0)).rgb;\n"
    "    vec3 C2 = texture(Source, TexCoord + vec2( dx, -dy)).rgb;\n"
    "    vec3 D3 = texture(Source, TexCoord + vec2(dx+dx,-dy)).rgb;\n"
    "    vec3 C3 = texture(Source, TexCoord + vec2(-dx,   0)).rgb;\n"
    "    vec3 C4 = texture(Source, TexCoord).rgb;\n"
    "    vec3 C5 = texture(Source, TexCoord + vec2( dx,   0)).rgb;\n"
    "    vec3 D4 = texture(Source, TexCoord + vec2(dx+dx, 0)).rgb;\n"
    "    vec3 C6 = texture(Source, TexCoord + vec2(-dx,  dy)).rgb;\n"
    "    vec3 C7 = texture(Source, TexCoord + vec2(  0,  dy)).rgb;\n"
    "    vec3 C8 = texture(Source, TexCoord + vec2( dx,  dy)).rgb;\n"
    "    vec3 D5 = texture(Source, TexCoord + vec2(dx+dx,dy)).rgb;\n"
    "    vec3 D0 = texture(Source, TexCoord + vec2(-dx,dy+dy)).rgb;\n"
    "    vec3 D1 = texture(Source, TexCoord + vec2(  0,dy+dy)).rgb;\n"
    "    vec3 D2 = texture(Source, TexCoord + vec2( dx,dy+dy)).rgb;\n"
    "    vec3 D6 = texture(Source, TexCoord + vec2(dx+dx,dy+dy)).rgb;\n"
    "\n"
    "    float c0=reduce(C0); float c1=reduce(C1); float c2=reduce(C2);\n"
    "    float c3=reduce(C3); float c4=reduce(C4); float c5=reduce(C5);\n"
    "    float c6=reduce(C6); float c7=reduce(C7); float c8=reduce(C8);\n"
    "    float d0=reduce(D0); float d1=reduce(D1); float d2=reduce(D2);\n"
    "    float d3=reduce(D3); float d4=reduce(D4); float d5=reduce(D5);\n"
    "    float d6=reduce(D6);\n"
    "\n"
    "    vec3 p00, p10, p01, p11;\n"
    "    if (c4 != c8) {\n"
    "        if (c7 == c5) {\n"
    "            p01 = C7; p10 = C7;\n"
    "            if ((c6==c7)||(c5==c2)) p00 = 0.25*(3.0*C7+C4);\n"
    "            else p00 = 0.5*(C4+C5);\n"
    "            if ((c5==d4)||(c7==d1)) p11 = 0.25*(3.0*C7+C8);\n"
    "            else p11 = 0.5*(C7+C8);\n"
    "        } else {\n"
    "            p11 = 0.125*(6.0*C8+C7+C5);\n"
    "            p00 = 0.125*(6.0*C4+C7+C5);\n"
    "            p10 = 0.125*(6.0*C7+C4+C8);\n"
    "            p01 = 0.125*(6.0*C5+C4+C8);\n"
    "        }\n"
    "    } else {\n"
    "        if (c7 != c5) {\n"
    "            p11 = C4; p00 = C4;\n"
    "            if ((c1==c4)||(c8==d5)) p01 = 0.25*(3.0*C4+C5);\n"
    "            else p01 = 0.5*(C4+C5);\n"
    "            if ((c8==d2)||(c3==c4)) p10 = 0.25*(3.0*C4+C7);\n"
    "            else p10 = 0.5*(C7+C8);\n"
    "        } else {\n"
    "            int r = 0;\n"
    "            r += GET_RESULT(c5,c4,c6,d1);\n"
    "            r += GET_RESULT(c5,c4,c3,c1);\n"
    "            r += GET_RESULT(c5,c4,d2,d5);\n"
    "            r += GET_RESULT(c5,c4,c2,d4);\n"
    "            if (r > 0) { p01=C7; p10=C7; p00=0.5*(C4+C5); p11=0.5*(C4+C5); }\n"
    "            else if (r < 0) { p11=C4; p00=C4; p01=0.5*(C4+C5); p10=0.5*(C4+C5); }\n"
    "            else { p11=C4; p00=C4; p01=C7; p10=C7; }\n"
    "        }\n"
    "    }\n"
    "    vec3 res = (fp.x < 0.5) ? (fp.y < 0.5 ? p00 : p10) : (fp.y < 0.5 ? p01 : p11);\n"
    "    FragColor = vec4(res, 1.0);\n"
    "}\n";

// --- Dot (Themaister) ---
static const char* kShaderDot =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "uniform vec2 TextureSize;\n"
    "uniform vec2 OutputSize;\n"
    "\n"
    "const float gamma = 2.4;\n"
    "const float shine = 0.05;\n"
    "const float blend = 0.65;\n"
    "\n"
    "float pixdist(vec2 coord, vec2 source) {\n"
    "    vec2 delta = coord - source;\n"
    "    return sqrt(dot(delta, delta));\n"
    "}\n"
    "\n"
    "float color_bloom(vec3 color) {\n"
    "    const vec3 gray_coeff = vec3(0.30, 0.59, 0.11);\n"
    "    float bright = dot(color, gray_coeff);\n"
    "    return mix(1.0 + shine, 1.0 - shine, bright);\n"
    "}\n"
    "\n"
    "vec3 lookup(vec2 pixel_no, float offset_x, float offset_y, vec3 color) {\n"
    "    vec2 offset = vec2(offset_x, offset_y);\n"
    "    float delta = pixdist(fract(pixel_no), offset + vec2(0.5, 0.5));\n"
    "    return color * exp(-gamma * delta * color_bloom(color));\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    vec2 pixel_no = TexCoord * TextureSize;\n"
    "    vec2 texel = 1.0 / TextureSize;\n"
    "    vec3 mid_color = lookup(pixel_no, 0.0, 0.0, texture(Source, TexCoord).rgb);\n"
    "    vec3 color = vec3(0.0);\n"
    "    color += lookup(pixel_no, -1.0, -1.0, texture(Source, TexCoord + vec2(-texel.x, -texel.y)).rgb);\n"
    "    color += lookup(pixel_no,  0.0, -1.0, texture(Source, TexCoord + vec2(0.0, -texel.y)).rgb);\n"
    "    color += lookup(pixel_no,  1.0, -1.0, texture(Source, TexCoord + vec2(texel.x, -texel.y)).rgb);\n"
    "    color += lookup(pixel_no, -1.0,  0.0, texture(Source, TexCoord + vec2(-texel.x, 0.0)).rgb);\n"
    "    color += mid_color;\n"
    "    color += lookup(pixel_no,  1.0,  0.0, texture(Source, TexCoord + vec2(texel.x, 0.0)).rgb);\n"
    "    color += lookup(pixel_no, -1.0,  1.0, texture(Source, TexCoord + vec2(-texel.x, texel.y)).rgb);\n"
    "    color += lookup(pixel_no,  0.0,  1.0, texture(Source, TexCoord + vec2(0.0, texel.y)).rgb);\n"
    "    color += lookup(pixel_no,  1.0,  1.0, texture(Source, TexCoord + vec2(texel.x, texel.y)).rgb);\n"
    "    vec3 out_color = mix(1.2 * mid_color, color, blend);\n"
    "    FragColor = vec4(out_color, 1.0);\n"
    "}\n";

// --- LCD Grid V2 (cgwg) ---
static const char* kShaderLcdGridV2 =
    "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D Source;\n"
    "uniform vec2 TextureSize;\n"
    "uniform vec2 OutputSize;\n"
    "\n"
    "#define RSUBPIX_R 1.0\n"
    "#define RSUBPIX_G 0.0\n"
    "#define RSUBPIX_B 0.0\n"
    "#define GSUBPIX_R 0.0\n"
    "#define GSUBPIX_G 1.0\n"
    "#define GSUBPIX_B 0.0\n"
    "#define BSUBPIX_R 0.0\n"
    "#define BSUBPIX_G 0.0\n"
    "#define BSUBPIX_B 1.0\n"
    "#define u_gain 1.5\n"
    "#define u_gamma 2.3\n"
    "#define u_blacklevel 0.0\n"
    "#define u_ambient 0.0\n"
    "#define outgamma 2.2\n"
    "\n"
    "float intsmear_func(float z, float coeffs[7]) {\n"
    "    float z2 = z*z;\n"
    "    float zn = z;\n"
    "    float ret = 0.0;\n"
    "    for (int i = 0; i < 7; i++) {\n"
    "        ret += zn*coeffs[i];\n"
    "        zn *= z2;\n"
    "    }\n"
    "    return ret;\n"
    "}\n"
    "\n"
    "float intsmear(float x, float dx, float d, float coeffs[7]) {\n"
    "    float zl = clamp((x-dx*0.5)/d,-1.0,1.0);\n"
    "    float zh = clamp((x+dx*0.5)/d,-1.0,1.0);\n"
    "    return d * ( intsmear_func(zh,coeffs) - intsmear_func(zl,coeffs) )/dx;\n"
    "}\n"
    "\n"
    "void main() {\n"
    "    float coeffs_x[7] = float[7](1.0, -2.0/3.0, -1.0/5.0, 4.0/7.0, -1.0/9.0, -2.0/11.0, 1.0/13.0);\n"
    "    float coeffs_y[7] = float[7](1.0, 0.0, -4.0/5.0, 2.0/7.0, 4.0/9.0, -4.0/11.0, 1.0/13.0);\n"
    "    vec2 texelSize = 1.0 / TextureSize;\n"
    "\n"
    "    vec3 outgamma3 = vec3(outgamma);\n"
    "    vec3 cred   = pow(vec3(RSUBPIX_R, RSUBPIX_G, RSUBPIX_B), outgamma3);\n"
    "    vec3 cgreen = pow(vec3(GSUBPIX_R, GSUBPIX_G, GSUBPIX_B), outgamma3);\n"
    "    vec3 cblue  = pow(vec3(BSUBPIX_R, BSUBPIX_G, BSUBPIX_B), outgamma3);\n"
    "\n"
    "    ivec2 tli = ivec2(floor(TexCoord/texelSize - vec2(0.4999)));\n"
    "\n"
    "    vec3 lcol, rcol;\n"
    "    float subpix = (TexCoord.x/texelSize.x - 0.4999 - float(tli.x))*3.0;\n"
    "    float rsubpix = 3.0 / TextureSize.x;\n"
    "    lcol = vec3(intsmear(subpix+1.0,rsubpix, 1.5, coeffs_x),\n"
    "               intsmear(subpix    ,rsubpix, 1.5, coeffs_x),\n"
    "               intsmear(subpix-1.0,rsubpix, 1.5, coeffs_x));\n"
    "    rcol = vec3(intsmear(subpix-2.0,rsubpix, 1.5, coeffs_x),\n"
    "               intsmear(subpix-3.0,rsubpix, 1.5, coeffs_x),\n"
    "               intsmear(subpix-4.0,rsubpix, 1.5, coeffs_x));\n"
    "\n"
    "    float tcol, bcol;\n"
    "    subpix = TexCoord.y/texelSize.y - 0.4999 - float(tli.y);\n"
    "    rsubpix = 1.0/TextureSize.y;\n"
    "    tcol = intsmear(subpix    ,rsubpix, 0.63, coeffs_y);\n"
    "    bcol = intsmear(subpix-1.0,rsubpix, 0.63, coeffs_y);\n"
    "\n"
    "    vec3 gain3 = vec3(u_gain);\n"
    "    vec3 gamma3 = vec3(u_gamma);\n"
    "    vec3 blacklevel3 = vec3(u_blacklevel);\n"
    "    vec3 ambient3 = vec3(u_ambient);\n"
    "    vec3 tcol3 = vec3(tcol);\n"
    "    vec3 bcol3 = vec3(bcol);\n"
    "\n"
    "    vec3 p00 = texture(Source, TexCoord - 0.25 * texelSize * vec2(0.0, 0.0)).rgb;\n"
    "    vec3 p11 = texture(Source, TexCoord - 0.25 * texelSize * vec2(1.0, 1.0)).rgb;\n"
    "    vec3 p01 = texture(Source, TexCoord - 0.25 * texelSize * vec2(0.0, 1.0)).rgb;\n"
    "    vec3 p10 = texture(Source, TexCoord - 0.25 * texelSize * vec2(1.0, 0.0)).rgb;\n"
    "\n"
    "    vec3 topLeftColor     = (pow(gain3 * p00 + blacklevel3, gamma3) + ambient3) * lcol * tcol3;\n"
    "    vec3 bottomRightColor = (pow(gain3 * p11 + blacklevel3, gamma3) + ambient3) * rcol * bcol3;\n"
    "    vec3 bottomLeftColor  = (pow(gain3 * p01 + blacklevel3, gamma3) + ambient3) * lcol * bcol3;\n"
    "    vec3 topRightColor    = (pow(gain3 * p10 + blacklevel3, gamma3) + ambient3) * rcol * tcol3;\n"
    "\n"
    "    vec3 averageColor = topLeftColor + bottomRightColor + bottomLeftColor + topRightColor;\n"
    "    averageColor = mat3(cred.x, cred.y, cred.z,\n"
    "                        cgreen.x, cgreen.y, cgreen.z,\n"
    "                        cblue.x, cblue.y, cblue.z) * averageColor;\n"
    "    FragColor = vec4(pow(averageColor, vec3(1.0/outgamma)), 1.0);\n"
    "}\n";

// ============================================================================
// Fragment Shader Dispatch
// ============================================================================
const char* GetShaderFragmentSource(ShaderType type)
{
    switch (type)
    {
    case ShaderType::LCD:                return kShaderLCD;
    case ShaderType::xBRZ:               return kShaderXBRZ;
    case ShaderType::Eagle:              return kShaderEagle;
    case ShaderType::Dot:                return kShaderDot;
    case ShaderType::LcdGridV2:          return kShaderLcdGridV2;
    case ShaderType::None:
    default:                             return kShaderNone;
    }
}
