name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-ps2:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add build-base cmake

    - name: Get Information Variables
      id: core
      run: |
        echo "::set-output name=info::$(echo mgba)"
        echo "::set-output name=platform::$(echo ps2)"
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Compile project
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DLIBMGBA_ONLY=ON -DBUILD_LIBRETRO=ON \
          -DLIBRETRO_STATIC=ON -DLIBRETRO_SUFFIX=_${{ steps.core.outputs.platform }} \
          -DBUILD_SHARED_LIBS=OFF -DPS2=ON \
          -DCMAKE_C_FLAGS="-DPS2 -DUSE_RGB565 -G0" -DCMAKE_CXX_FLAGS="-DPS2 -DUSE_RGB565 -G0" \
          -DCMAKE_TOOLCHAIN_FILE=/usr/local/ps2dev/ps2sdk/ps2dev.cmake . -Bbuild
        cmake --build build --target ${{ steps.core.outputs.info }}_libretro -- -j$(nproc)
        cp build/${{ steps.core.outputs.info }}_libretro_${{ steps.core.outputs.platform }}.a .

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.core.outputs.info }}_libretro_${{ steps.core.outputs.platform }}-${{ steps.core.outputs.sha8 }}
        path: ${{ steps.core.outputs.info }}_libretro_${{ steps.core.outputs.platform }}.a
